services:
  postgres:
    container_name: postgres
    restart: always
    build: 
      context: ./postgres
      dockerfile: Dockerfile
    environment:
      POSTGRES_DB: zntsystem
      POSTGRES_USER: zntsystem
      POSTGRES_PASSWORD: zntsystem
    expose:
      - 5432
    ports:
      - "5432:5432"
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
      - ./postgres/dump.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - project-network

  zenith-api:
    container_name: zenith-api
    restart: always
    build:
      context: ./academia-api
      dockerfile: Dockerfile.dev
    depends_on:
      - postgres
    environment:
      DB_CONNECTION: pgsql
      DB_HOST: postgres
      DB_PORT: 5432
      DB_DATABASE: zntsystem
      DB_USERNAME: zntsystem
      DB_PASSWORD: zntsystem
    volumes:
      - ./academia-api:/var/www/html
    expose:
      - 80
    networks:
      - project-network

  zenith-web:
    container_name: zenith-web
    restart: always
    build:
      context: ./academia-web
      dockerfile: Dockerfile.prod
    depends_on:
      - zenith-api
    volumes:
      - ./academia-web:/app
    expose:
      - 3000
    networks:
      - project-network

  nginx:
    container_name: nginx
    restart: always
    build:
      context: ./nginx
      dockerfile: Dockerfile
    depends_on:
      - zenith-api
      - zenith-web
    ports:
      - "80:80"
    volumes:
      - ./nginx/logs:/etc/nginx/logs
    networks:
      - project-network


networks:
  project-network:
    driver: bridge