services:
  postgres:
    container_name: postgres
    restart: always
    build: 
      context: ./postgres
      dockerfile: Dockerfile
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    expose:
      - 5432
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
      - ./postgres/dump.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - project-network

  zenith-api:
    container_name: zenith-api
    restart: always
    build:
      context: ./zenith-api
      dockerfile: Dockerfile.prod
    depends_on:
      - postgres
    environment:
      DB_CONNECTION: pgsql
      DB_HOST: postgres
      DB_PORT: 5432
      DB_DATABASE: postgres
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
    networks:
      - project-network
    expose:
      - 80

  zenith-web:
    container_name: zenith-web
    restart: always
    build:
      context: ./academia-web
      dockerfile: Dockerfile.prod
    depends_on:
      - zenith-api
    expose:
      - 3000
    networks:
      - project-network

  nginx:
    container_name: nginx
    restart: always
    build:
      context: ./nginx
      dockerfile: Dockerfile
    depends_on:
      - zenith-api
      - zenith-web
    ports:
      - "80:80"
    volumes:
      - ./nginx/logs:/etc/nginx/logs
    networks:
      - project-network


networks:
  project-network:
    driver: bridge